name: "Hello World"
description: "Greet someone and record the time"
inputs:
  access_token:
    description: "GitHub PAT"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.access_token }}
