on: [push]

jobs:
  docker-test:
    runs-on: ubuntu-latest
    name: Docker container action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./.github/actions/repository-dispatch/
        id: hello
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          who_to_greet: "Mona the Octocat"
