on: [push]

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  non-docker-test:
    runs-on: ubuntu-latest
    name: Non-Docker container action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clone remote repo
        run: |
          git clone --depth 1 \
            "https://${{ secrets.ACCESS_TOKEN }}@github.com/gsong/dispatch-a.git" \
            /tmp/dispatch-a
      - name: Debug
        run: |
          env
          echo "/tmp/dispatch-a"
          (cd /tmp/dispatch-a && ls -al)
          (cd /tmp/dispatch-a && git remote -v)
          echo "${GITHUB_WORKSPACE}"
          (cd "${GITHUB_WORKSPACE}" && ls -al)
          (cd "${GITHUB_WORKSPACE}" && git remote -v)
