name: Remote Dispatch Action Responder

on: [repository_dispatch]

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"

      - name: PONG - Dispatch response to received PING
        if: github.event.action == 'ping'
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: ${{github.event.client_payload.repository}}
          event-type: pong
          client-payload: '{ "repository": "${{ github.repository }}" }'
          token: ${{ secrets.ACCESS_TOKEN }}
